name: Run Chaos Tests
on:
  schedule:
    # Runs every 3 hours on the hour
    - cron: "0 */3 * * *"
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  chaos-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.6"

      - name: Download dependencies
        run: go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run chaos tests
        run: go vet ./... && go test -v -race -timeout 60m -count=1 -skip 'TestCancellationChaos' ./...
        working-directory: ./chaos_tests
        env:
          PGPASSWORD: a!b@c$d()e*_,/:;=?@ff[]22
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
